# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.21"
  amd64: "ghcr.io/home-assistant/amd64-base:3.21"
  armhf: "ghcr.io/home-assistant/armhf-base:3.21"
  armv7: "ghcr.io/home-assistant/armv7-base:3.21"
  i386: "ghcr.io/home-assistant/i386-base:3.21"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Step-ca add-on"
  org.opencontainers.image.description: "Step-ca add-on to use as private certificate authority."
  org.opencontainers.image.source: "https://github.com/hobbypunk90/homeassistant-addon-step-ca"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  STEP_CA_VERSION: "0.28.3"
